TestePRODAM/Controllers/FornecedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestePRODAM.Data;
using TestePRODAM.Models;

namespace TestePRODAM.Controllers
{
    public class FornecedoresController : Controller
    {
        private readonly TesteProdamContext _context;

        public FornecedoresController(TesteProdamContext context)
        {
            _context = context;
        }

        // GET: Fornecedores
        [Route("lista-de-fornecedores")]
        public async Task<IActionResult> Index(string busca)
        {
            var fornecedores = from f in _context.Fornecedores.Include("Empresa")                              
                               select f;

            if (!String.IsNullOrEmpty(busca))
            {
                fornecedores = fornecedores.Where(
                    s => s.Nome.Contains(busca) || 
                    s.Documento.Contains(busca));                
            }          

            return View(await fornecedores.ToListAsync());
            //var testeProdamContext = _context.Fornecedores.Include(f => f.Empresa);
            //return View(await testeProdamContext.ToListAsync());
        }

        // GET: Fornecedores/Details/5
        [Route("dados-do-fornecedor/{id:guid}")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _context.Fornecedores
                .Include(f => f.Empresa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }

        // GET: Fornecedores/Create
        [Route("novo-fornecedor")]
        public IActionResult Create()
        {
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Nome");
            return View();
        }

        // POST: Fornecedores/Create        
        [Route("novo-fornecedor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Fornecedor fornecedor)
        {            
            if (ModelState.IsValid)
            {                
                _context.Add(fornecedor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Nome", fornecedor.EmpresaId);
            return View(fornecedor);
        }

        // GET: Fornecedores/Edit/5
        [Route("editar-fornecedor/{id:guid}")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _context.Fornecedores.FindAsync(id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Nome", fornecedor.EmpresaId);
            return View(fornecedor);
        }

        // POST: Fornecedores/Edit/5
        [Route("editar-fornecedor/{id:guid}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Fornecedor fornecedor)
        {
            if (id != fornecedor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fornecedor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FornecedorExists(fornecedor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Documento", fornecedor.EmpresaId);
            return View(fornecedor);
        }

        // GET: Fornecedores/Delete/5
        [Route("excluir-fornecedor/{id:guid}")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _context.Fornecedores
                .Include(f => f.Empresa)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }

        // POST: Fornecedores/Delete/5
        [Route("excluir-fornecedor/{id:guid}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var fornecedor = await _context.Fornecedores.FindAsync(id);
            _context.Fornecedores.Remove(fornecedor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FornecedorExists(Guid id)
        {
            return _context.Fornecedores.Any(e => e.Id == id);
        }
    }
}

TestePRODAM/Views/Fornecedores/Create.cshtml
@model TestePRODAM.Models.Fornecedor

@{
    ViewData["Title"] = "Novo Fornecedor";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
      <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
          <label asp-for="EmpresaId" class="control-label">Empresa</label>
          <select asp-for="EmpresaId" class="form-control" asp-items="ViewBag.EmpresaId"></select>
        </div>
        <div class="form-group">
          <label asp-for="Nome" class="control-label">Nome do Fornecedor</label>
          <input asp-for="Nome" class="form-control" />
          <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group">
          <label asp-for="Documento" class="control-label"></label>
          <input asp-for="Documento" class="form-control" />
          <span asp-validation-for="Documento" class="text-danger"></span>
        </div>
        <div class="form-group">
          <label asp-for="TipoFornecedor" class="control-label"></label><br />
          <input type="radio" value="1" asp-for="TipoFornecedor" checked onclick="mostraCamposPessoaFisica();" /> Pessoa Física<br />
          <input type="radio" value="2" asp-for="TipoFornecedor" onclick="escondeCamposPessoaFisica();"/> Pessoa Jurídica
        </div>
        <div class="form-group">
          <label asp-for="DataCadastro" class="control-label"></label>
          <input asp-for="DataCadastro" class="form-control" />
          <span asp-validation-for="DataCadastro" class="text-danger"></span>
        </div>
        <div id="pessoaFisica">
          <div class="form-group">
            <label asp-for="RG" class="control-label"></label>
            <input asp-for="RG" class="form-control" />
            <span asp-validation-for="RG" class="text-danger"></span>
          </div>
          <div class="form-group">
            <label asp-for="DataNascimento" class="control-label"></label>
            <input asp-for="DataNascimento" class="form-control" />
            <span asp-validation-for="DataNascimento" class="text-danger"></span>
          </div>
        </div>

        <div class="form-group">
          <label asp-for="Telefone" class="control-label"></label>
          <input asp-for="Telefone" class="form-control" />
          <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>

        <div class="form-group">
          <label asp-for="Celular" class="control-label"></label>
          <input asp-for="Celular" class="form-control" />
          <span asp-validation-for="Celular" class="text-danger"></span>
        </div>
        <div class="form-group">
          <input type="submit" value="Adicionar Fornecedor" class="btn btn-primary" />
        </div>
      </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Voltar para a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
  escondeCamposPessoaFisica();
  mostraCamposPessoaFisica();
</script>
}

TestePRODAM/Views/Fornecedores/Delete.cshtml
@model TestePRODAM.Models.Fornecedor

@{
    ViewData["Title"] = "Excluir Fornecedor";
}

<h1>@ViewData["Title"]</h1>

<h3>Tem certeza que deseja excluir?</h3>
<div>    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoFornecedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoFornecedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empresa.Documento)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-info">Voltar para a lista</a>
    </form>
</div>

TestePRODAM/Views/Fornecedores/Details.cshtml
@model TestePRODAM.Models.Fornecedor

@{
  ViewData["Title"] = "Detalhes do Fornecedor";
}

<h1>@ViewData["Title"]</h1>

<div>  
  <hr />
  <dl class="row">
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Nome)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Nome)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Documento)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Documento)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.TipoFornecedor)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.TipoFornecedor)
    </dd>
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.DataCadastro)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.DataCadastro)
    </dd>   
      <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.RG)
      </dt>
      <dd class="col-sm-10">
        @Html.DisplayFor(model => model.RG)
      </dd>
      <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.DataNascimento)
      </dt>
      <dd class="col-sm-10">
        @Html.DisplayFor(model => model.DataNascimento)
      </dd>    
    <dt class="col-sm-2">
      @Html.DisplayNameFor(model => model.Empresa)
    </dt>
    <dd class="col-sm-10">
      @Html.DisplayFor(model => model.Empresa.Nome)
    </dd>
  </dl>
</div>
<div>
  <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Editar</a>
  <a asp-action="Index" class="btn btn-info">Voltar para lista</a>
</div>

@section Scripts {
  @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
}

TestePRODAM/Views/Fornecedores/Edit.cshtml
@model TestePRODAM.Models.Fornecedor

@{
    ViewData["Title"] = "Editar Fornecedor";
}

<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpresaId" class="control-label">Empresa</label>
                <select asp-for="EmpresaId" class="form-control" asp-items="ViewBag.EmpresaId"></select>
                <span asp-validation-for="EmpresaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documento" class="control-label"></label>
                <input asp-for="Documento" class="form-control" />
                <span asp-validation-for="Documento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoFornecedor" class="control-label"></label>
                <select asp-for="TipoFornecedor" asp-items="@Html.GetEnumSelectList<TipoFornecedor>()" class="form-control">
                  <option selected="selected" value=""></option>
                </select>
                
                <span asp-validation-for="TipoFornecedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataCadastro" class="control-label"></label>
                <input asp-for="DataCadastro" class="form-control" />
                <span asp-validation-for="DataCadastro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RG" class="control-label"></label>
                <input asp-for="RG" class="form-control" />
                <span asp-validation-for="RG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Voltar para a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestePRODAM/Views/Fornecedores/Index.cshtml
@model IEnumerable<TestePRODAM.Models.Fornecedor>

@{
    ViewData["Title"] = "Lista de Fornecedores";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Fornecedores" asp-action="Index">
  <p>
    <input type="text" name="busca" placeholder="Nome ou Documento"/>
    <input type="submit" value="Filtrar" />
  </p>
</form>

<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoFornecedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataCadastro)
            </th>            
            <th>
                @Html.DisplayNameFor(model => model.Empresa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Documento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoFornecedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCadastro)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.Empresa.Nome)
            </td>
            <td class="text-right">
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Editar</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Detalhes</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

<p>
  <a asp-action="Create" class="btn btn-success">Novo Fornecedor</a>
</p>